version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: finsage-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finsagedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: